### PR TITLE
refactor code to load modules normally

### PR DESCRIPTION
**Pull request by ericphanson**
I noticed when developing https://github.com/OxygenFramework/Oxygen.jl/pull/158 the tests showed a lot of messages like
```julia
WARNING: Method definition get(Function, String) in module Core at /Users/eph/Oxygen.jl/src/core.jl:504 overwritten in module Core on the same line (check for duplicate calls to `include`).
WARNING: Method definition get(Function, Function) in module Core at /Users/eph/Oxygen.jl/src/core.jl:505 overwritten in module Core on the same line (check for duplicate calls to `include`).
```

This fixes some of them by loading the module once.

A rule of thumb in Julia is each file should be `include`ed exactly once. Each time you `include` a module, it creates a separate copy of it. Instead, we should use relative `using` statements like `using ..Util`. See [this section](https://docs.julialang.org/en/v1/manual/modules/#Submodules-and-relative-paths) of the Julia manual for more.

I suspect some of this is to facillitate a testing workflow. I wonder if perhaps you aren't using [Revise](https://github.com/timholy/Revise.jl), and thus reinclude the source code to reload it? 

I would highly recommend Revise for this, it is even mentioned in the main Julia manual: https://docs.julialang.org/en/v1/manual/workflow-tips/#Revise-based-workflows.

### CODE REVIEW

**Comment by ericphanson** [comment]
I see https://github.com/OxygenFramework/Oxygen.jl/pull/158 does some of this refactoring as well. This PR just refactors the `include`s to `using`s without touching anything else, so I think it could make sense alone, and adding features like #158 could be built on top of it.

**Comment by JanisErdmanis** [comment]
This is pretty much covered in #158 refactor. I also added show_errors keyword to serve and added suppression of errors at the call site on internalrequest which expects errors.

**Comment by ericphanson** [comment]
I think using `@test_logs` as in #161 is a better approach than `@suppress`, because it additionally tests that those log messages are indeed being emitted as expected.

**Comment by ndortega** [comment]
Sorry about the bad timing, most of these changes have already been addressed in the previous merge request. I plan on closing this PR for now simply due to the number of merge conflicts to resolve. I'll make sure to fix the imports in the demo files in the next pr.

**Pull request closed without merging**
