### PR TITLE
bugfix/relocatability-fix

### PR DESCRIPTION
**Pull request by ndortega**
added a new PACKAGE_DIR const using the `@path` macro from RelocatableFolders
Related: #184

### CODE REVIEW

**Comment by ndortega** [comment]
@JanisErdmanis 
Try this branch out and let me know if this fixes your issue.

**Comment by JanisErdmanis** [comment]
I can report that this solves the issue. Though the testing is a bit indirect since I need to add the Oxygen to the project since otherwise it get's resolved from registry. 

It would be great if you could bump a minor release with this change here, so I could confirm this with a direct test.

**Comment by ndortega** [comment]
@JanisErdmanis It's published under v1.5.5, let me know if it's working as expected

**Comment by JanisErdmanis** [comment]
Works as expected

**Pull request merged**
