### PR TITLE
feature/oxidise-context-refactor

### PR DESCRIPTION
**Pull request by ndortega**
- Refactored context struct
- Added new `instance()` function to dynamically create multiple instances
- Fixed cron and repeat task internals
- moved docspath and schemapath into the docs part of the Context
- Metrics middleware no longer catches errors thrown inside middleware chains
- added a dynamic parser generation for routes defined outside the oxygen internals.

### CODE REVIEW

**Comment by JanisErdmanis** [comment]
> 1.) moved docs and metrics setup into the serve and serveparallel handlers() this was causing a world age problem in julia when using the internalrequest() function

Can you provide a test example where the world age problem surfaces? 

I am very sad to see you have refactored the context in spite of my arguments not to do so. Even if I take the point of view that it is done to promote separation of concerns, I do, however, want to point out a few inconsistencies I have noticed with the approach:

- `mountedfolders` are with `Documentation` struct. In what sense a user hosting files with `dynamicfiles` or `staticfiles` always is documentation?
- there is now a coupling for `Cron` module with the `Context` object. There is an easy fix, as you could pass `CronRuntime` to the struct directly. 

Also, by reverting the change of having a documentation middleware created at runtime, warnings would rise withtin `HTTP.register!` in case of repeated serve. Your only option here, thus, is to put back the `@suppress` macro, which, in my opinion, is a significant downgrade in code quality. 

Metrics and documentation are sometimes better served by the service's admin panel. In my situation, it is hosted on a separate router object. Making that work with the current codebase is going to take more work. 

After this pull request, I see myself struggling with the codebase more than if I would maintain my fork of it.

**Comment by ndortega** [comment]
The world issue was happening during the automated tests because the router & middleware were getting setup and immediately called during a internalrequest() call. This can lead to a "world age" issue when you define a method and then immediately try to call it within the same scope. There are several places we could move the docs & metrics setup that isn't the setupmiddleware function.

<hr>

I meant no offense by refactoring the context like it is. I did so based on the following principles

**Don't repeat yourself**

I found myself having to pass both service and context objects to internal methods to access both runtime and static properties. Generally, when I see myself repeating the same thing multiple times It throws up a red flag that these need to be grouped. 

**Separation of Concerns** 

All related properties are grouped together under the same prefix, which makes it easy to keep track of what's relevant to each module. For example, any new contributor looking at the project can now just look at a single file and see where all cron-related properties are located. Runtime variables that are subject to change can be identified by the Ref object in the type definition.

<hr>

To address the rest of your points:

- `mountedfolders` is always used in the context of documentation. Its only purpose in the codebase is to tell us whether or not to generate open-api docs for this endpoint. 
- You're right, There's no real reason why we can't pass the values instead of the context to functions (like in the cron module)
- I think there's a couple options we could take to prevent warning from showing up around mounting the same documentation routes. 
  - Inject the dynamic docs middleware outside the setupmiddlware function and place it in the serve functions
  - use the Supressor library to hide these warnings
  - Prevent docs endpoints from getting mounted more than once using runtime checks
  - Use the command pattern to collect all the request handlers and then delay the actual registration until we run serve. This would allow us to create a brand new Router for each serve() call. 
 
<hr>

If you need to show metrics from one instance on another, nothing done so far would make this easily possible. But we can look into customizing it.

**Comment by JanisErdmanis** [comment]
> The world issue was happening during the automated tests because the router & middleware were getting setup and immediately called during a internalrequest() call. This can lead to a "world age" issue when you define a method and then immediately try to call it within the same scope. 

This couldn’t be true because SERVICE is assigned after the return value of serve; also, no eval is involved when defining methods or generated functions. I hadn’t seen a single test fail after the documentation was constructed in a middleware. If we faced the “world age” issue every time we defined the function and called at the same scope, anonymous functions wouldn’t work! Perhaps you do have an example to counter my statement. 

> I found myself having to pass both service and context objects to internal methods to access both runtime and static properties. Generally, when I see myself repeating the same thing multiple times It throws up a red flag that these need to be grouped.

There was a significant amount of code where the `Context` was passed individually. There were also never more than two arguments in the call signature. 

> mountedfolders is always used in the context of documentation. Its only purpose in the codebase is to tell us whether or not to generate open-api docs for this endpoint.

Thanks for making that clear.

> I think there's a couple options we could take to prevent warning from showing up around mounting the same documentation routes.

These options either add burden to the user, downgrade code quality with suppression, or add more state management in the code, increasing complexity. I have never seen a world-age issue when constructing documentation at runtime. 

> If you need to show metrics from one instance to another, nothing done so far would make this easily possible. But we can look into customising it.

```
setupmetrics(router::Router, history::History, docspath::String)
```

This was the function signature there was before your refactor of the Context. If one needs it, it can simply be registered statically to the codebase by the user when taking a history object of another instance. You may revert to that single function, but what I am saying is that the issue is systematic - if you need a banana, you don’t also need a gorilla holding the banana and the whole jungle.

**Comment by ndortega** [comment]
Hi Janis, 

Sorry about the first point, you're right on that one. I was testing an experimental parser generator which would create a parser designed for each route with path parameters at the time of registration. While this did improve performance it ended up causing world age issues when any routes were setup internally with path params. 

In my latest commit I decoupled the cron & repeat tasks module from the context type and exported the setupdocs and setupmetrics functions with the original function signatures. Like you mentioned, the old signature should make it possible to intercept requests. 

I also added Suppressor back in, but this time it only supresses warnings on internally defined routes lik metrics, docs and static files

Take a look and let me know what you think.

**Comment by JanisErdmanis** [comment]
The result is better, but it only fixes symptoms over the overall problems introduced by the Context refactor. 
For instance, I don’t see in the call signatures methods attached to the `Service` type. I can also ask why the `Cron` module needs to know about `cronjobs`, which, from its perspective, is simply redundant.  The number of variables necessary to call a function on average has increased as your refactored Context object also includes runtime parameters, hence the gorilla and the jungle.

In contrast, when runtime parameters are constructed at runtime, the number of parameters in the function call signature one needs to set or initialise is reduced, making them more versatile and more accessible to reason about. 

Placing back `@suppressor` or doing a runtime check on whether cronjobs have already been placed within `job_definitions` is a simple way to hide issues under the rug. These are inferior solutions to what there were before your refactor. 

> I was testing an experimental parser generator which would create a parser designed for each route with path parameters at the time of registration. While this did improve performance it ended up causing world age issues when any routes were setup internally with path params.

Regarding the parser, it seems like a cool project to explore. I would be willing to hear about the world age, which has risen because of the documentation that is being generated at runtime. Perhaps that can change my mind on why this pull request is necessary.

**Comment by JanisErdmanis** [comment]
> The registercronjobs function goes and takes these values and creates a lambda with internalrequest() and then adds them to the same job_definitions array (now that it has a callable function)

This adds unnecessary coupling between the cron module and the core. It would be much better to store the function pointer, which gets called just like in `job_definitions`.  I did refactor out the cronjobs by passing the “cronjob” variable through `parse_route` which was admittedly an add-hoc solution but could be polished with an appropriate `Path` type. It does not matter whether there are one or two variables, but rather that jobs can be started with `CronContext` alone without relying on `registercronjobs` at runtime. 

> In hindsight, I should switch the names around since cronjobs sound like it holds executable cronjobs while job_definitions sounds like it only holds the definitions of the job.

I agree that these names should be switched.

> The main reason for the context refactor from my end was the added complexity, which made it harder to debug. For example, in the current master branch, both the cron module and repeat tasks are not working - you can start but can't stop running jobs or tasks

If I understand correctly, this is because the pointer to running cronjobs is only initialised during a serve and is not updated when one stops and starts cronjobs, as I relied on return values. The fix to that would be to allow `Service` (master branch) to have the following signature:
```
mutable struct Service
	context::Context
	history::History
	cron::Union{CronRuntime, Nothing}
	tasks::Union{TasksRuntime, Nothing}
	server::Union{HTTP.Server, Nothing}
	# also parallelhandler
end
``` 
Initialise it at the global scope and attach methods like:
```
SERVICE = Service()

function startcronjobs()
	SERVICE.cron = Core.startcronjobs(SERVICE.context.cron)
end

function serve(args…, kwargs…)
	
	service = Core.serve(SERVICE.context, args…, kwargs…)

	SERVICE.history = service.history
	SERVICE.cron = service.cron
	SERVICE.tasks = service.tasks
	SERVICE.server = service.server
	
	return service
end
```
which would also leave a single global constant as in your refactor. 

I highly prefer `Base.close(service)` over `Base.close(context)` as well as the start and restart service, as it is referred to within UNIX. 

Regarding your last point, one can do deprecation gracefully by introducing a deprecation message informing that the call has an overhead in comparison to macro syntax and then see how much the users really want it.

**Comment by ndortega** [comment]
Also, don't worry about the suppressor - I'm going to update this PR to move it back as a test dependency in favor of the DocsMiddleware function during my lunch

**Comment by ndortega** [comment]
Hi @JanisErdmanis, 

I'm going to merge this for now, but I think this is a good next step for the internal refactor. At least with this iteration, all the important internal properties are present in the same file which would make the refactor you were talking about easier. At the end of the day I care most about working code, so if you can reorganize the states to make it more readable and maintainable - go right ahead.  

I've already switched over to the `Base.close(service)` approach and have also upgraded the `format_response!` to have a new branch dedicated towards julia primitives (rather than relying on json3 to parse them). This means that code that's returning a single string, number or symbol will return it with a plain/text content type rather than a json mime type when the content isn't a properly formated json object

**Pull request merged**
